version: '3.3'

volumes:
  postgres_data:
  static_dir:
  media_dir:

services:
  db:
    container_name: db
    image: postgres:13.10
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
  backend:
    container_name: foodgram_backend
    image: ilyayandex/foodgram_backend:latest
    volumes:
      - static_dir:/backend_static/
      - media_dir:/app/media/
    env_file:
      - .env
  frontend:
    container_name: foodgram_frontend
    image: ilyayandex/foodgram_frontend:latest
    volumes:
      - ./frontend/:/app/result_build/



  nginx:
    container_name: gateway
    image: nginx:1.19.3
    restart: always
    ports:
       - 8000:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_dir:/etc/nginx/html/static/
      - media_dir:/etc/nginx/html/media/
    depends_on:
      - backend
      - frontend
