# Generated by Django 3.2 on 2023-10-23 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20231020_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.CharField(max_length=255, verbose_name='Пароль'),
        ),
    ]
